server:
  port: 8088
spring:
  profiles:
    active: dev
debug: true

---

Person:
  name: leo
  age: ${random.int(30)}
  job: testing engineer（测试开发工程师）
  habit:
    - coding
    - learning
    - play games
    - skateBoarding
    - ${Person.job}

---
# 日志配置
logging:
  path: /SpringbootLog