server:
  port: 8088
spring:
  profiles:
    active: dev
---

Person:
  name: 龙官文
  age: ${random.int(30)}
  job: testing engineer（测试开发工程师）
  habit:
    - coding
    - learning
    - play games
    - skateBoarding
    - ${Person.job}